data_path: 'data'
pd_dir: 'pd_sb'
healthy_dir: 'healthy_sb'
mat_dict: 'dataSorted'
classic_prepro : False
pd_subjects: []
healthy_subjects : [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
batch_size: 64
n_hidden_nodes : 128
n_hidden_layers: 2
lr: 0.001
epochs: 500
experiments_dir : 'mlp_lightning_logs'
